"""Local proposals and auditable opportunity scores; no Luma API or messages."""
import sqlite3,json,csv,hashlib,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];c=sqlite3.connect(ROOT/'dataset.sqlite');c.row_factory=sqlite3.Row
E=[dict(r) for r in c.execute('SELECT e.*,m.city,m.country_normalized,m.category,m.source_family,m.latitude,m.longitude,s.url source_url FROM canonical_event_editions e JOIN scale_event_metadata m ON e.id=m.event_id JOIN sources s ON s.id=e.source_id')]
facts=[json.loads(x) for x in (ROOT/'batches/enrichment.jsonl').read_text().splitlines()]
CASES=[{'id':'clickhouse','company':'ClickHouse','url':'https://clickhouse.com/','terms':['data','cloud','devops','kubernetes','observability','sql'],'title':'De los logs a una decisión: laboratorio de analítica operativa','objective':'Escenario a validar: 20 conversaciones técnicas consentidas con equipos de plataforma','icp':'Hipótesis: platform engineers, SRE y responsables de analítica en empresas B2B de Europa','budget':8000,'audience':40,'sponsors':['AWS','Google Cloud','Grafana Labs'],'agenda':[('18:00','Recepción y presentación de problemas de observabilidad'),('18:15','Demostración: consultas analíticas sobre telemetría anonimizada'),('18:40','Laboratorio guiado: latencia, coste y diseño del esquema'),('19:20','Discusión de arquitecturas y preguntas'),('19:45','Networking con inscripción opcional para seguimiento')],'body':'Un encuentro práctico para equipos que necesitan convertir señales operativas en decisiones. Trabajaremos con datos de demostración, compararemos decisiones de arquitectura y compartiremos los límites de cada enfoque. Trae tu portátil y una pregunta técnica; no necesitas traer datos de tu empresa.'},
{'id':'snowflake','company':'Snowflake','url':'https://www.snowflake.com/','terms':['python','pycon','data','ai','analytics'],'title':'Del prototipo Python al producto de datos: clínica de arquitectura','objective':'Escenario a validar: 15 conversaciones consentidas con equipos que operan productos de datos','icp':'Hipótesis: data engineers y desarrolladores Python de empresas B2B europeas','budget':12000,'audience':50,'sponsors':['AWS','JetBrains','Red Hat'],'agenda':[('18:00','Bienvenida y problemas que queremos resolver'),('18:15','Caso técnico: calidad, gobierno y costes en un pipeline Python'),('18:40','Clínica en grupos: revisar una arquitectura de referencia'),('19:15','Puesta en común: decisiones y compromisos'),('19:40','Conversaciones abiertas y próximos pasos opcionales')],'body':'Una sesión de trabajo para pasar de un prototipo a un producto de datos operable. Revisaremos una arquitectura de referencia, discutiremos calidad y gobierno, y pondremos números a las decisiones de coste. Usaremos ejemplos de demostración; no compartas información confidencial de tu empresa.'}]
def js(x):return json.dumps(x,ensure_ascii=False,separators=(',',':'))
def insert(t,d):
 keys=list(d);c.execute('INSERT OR REPLACE INTO '+t+' ('+','.join(keys)+') VALUES ('+','.join('?' for _ in keys)+')',[d[k] for k in keys])
def csvout(p,rs):
 if not rs:return
 with p.open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rs[0]));w.writeheader();w.writerows(rs)
allrows=[];report=['# Dos flujos URL → evidencia → propuesta → borrador local','Fecha de evaluación: 28-09-2026. Los datos de empresa y eventos son publicados; objetivos, ICP, capacidad, presupuesto y concepto son escenarios propios pendientes de validación. No representan instrucciones de un cliente real. Ningún sponsor ha sido contactado ni ha confirmado interés.']
for case in CASES:
 profile=next(x for x in facts if x['kind']=='company_profile' and x['company_name']==case['company'])
 eligible=[]
 for e in E:
  if e['source_family']=='helsinki_linked_events' or not '2026-10-28'<=e['start_date']<'2027-04-01':continue
  text=(e['title']+' '+(e['topics_json'] or '')).lower();matches=[t for t in case['terms'] if t in text]
  if not matches:continue
  region=20 if e['country_normalized'] in ['Germany','United Kingdom','Netherlands'] else 0
  topic=min(40,20*len(matches));schedule=15;identity=10 if e.get('canonical_url') else 0
  sponsor_count=c.execute("SELECT count(distinct company_id) FROM event_company_roles WHERE event_id=? AND role='sponsor'",(e['id'],)).fetchone()[0]
  sponsorship=15 if sponsor_count else 0
  components={'term_fit':topic,'target_region_scenario':region,'date_window':schedule,'published_event_url':identity,'named_sponsor_evidence':sponsorship}
  score=sum(components.values());row={'case':case['id'],'event_id':e['id'],'title':e['title'],'start_date':e['start_date'],'country':e['country_normalized'],'city':e['city'],'score':score,'components_json':js(components),'matched_terms_json':js(matches),'source_url':e['source_url'],'event_url':e['canonical_url'],'latitude':e['latitude'],'longitude':e['longitude'],'interpretation':'research_priority_not_probability_or_ROI','missing':'price; availability; verified ICP attendance; current sponsor interest'};eligible.append(row)
 eligible.sort(key=lambda e:(-e['score'],e['start_date'],e['event_id']));short=eligible[:10];allrows.extend(short)
 sponsor=[]
 for name in case['sponsors']:
  rs=list(c.execute("SELECT co.name,e.title,e.start_date,r.level,s.url,r.id FROM event_company_roles r JOIN companies co ON co.id=r.company_id JOIN event_editions e ON e.id=r.event_id JOIN sources s ON s.id=r.source_id WHERE lower(co.name)=lower(?) AND r.role='sponsor' ORDER BY e.start_date DESC LIMIT 3",(name,)))
  for r in rs:sponsor.append({'candidate_name':r[0],'historic_event':r[1],'date':r[2],'level':r[3],'source_url':r[4],'role_id':r[5],'interest':'unknown','commercial_conflict':'needs_customer_review','reason':'Published historical sponsor; thematic partnership is an unverified hypothesis'})
 budget={'currency':'EUR','basis':'illustrative scenario, not quotes or client budget','venue_av':int(case['budget']*.3),'food':int(case['budget']*.2),'facilitation_content':int(case['budget']*.2),'distribution':int(case['budget']*.15),'contingency':int(case['budget']*.15)}
 assert sum(v for v in budget.values() if isinstance(v,int))==case['budget']
 pending=['Customer objective and success metric','Exact ICP and region','Confirmed budget and currency','Date, venue and capacity','Organizer identity and speakers','Sponsor fit, conflicts and interest','Consent and privacy copy for follow-up']
 scenario={'company_url':case['url'],'public_profile':{'value':profile['value'],'source_url':profile['source_url'],'observed_at':profile['observed_at'],'assertion_id':profile['assertion_id']},'requires_user_input':pending,'assumptions':{'objective':case['objective'],'icp':case['icp'],'region':'Germany / Berlin pilot hypothesis','budget':case['budget'],'currency':'EUR','capacity':case['audience']},'shortlist':short,'sponsor_shortlist':sponsor,'proposed_agenda':case['agenda'],'illustrative_budget':budget,'gtm_plan':[{'when':'T-6 weeks','action':'Validate ICP with five customer interviews; confirm venue/date and explicit organizer permission'},{'when':'T-4 weeks','action':'Publish approved registration page; invite via owned channels and communities with their permission'},{'when':'T-2 weeks','action':'Share technical demo preview; track source-tagged registrations, not inferred attendance'},{'when':'event day','action':'Separate registrations, check-ins, capacity and opt-in follow-up'},{'when':'T+2 days','action':'Send promised material only to opted-in registrants; collect usefulness feedback'},{'when':'T+30 days','action':'Review consented conversations and attributable next steps without claiming causal ROI'}],'score_version':'rule-v1','score_definition':'0..100 = min(40,20 per matched term)+20 scenario region+15 date eligibility+10 published event URL+15 observed named sponsors. Zero sponsor component means no evidence in corpus, not no sponsors.'}
 (ROOT/'examples'/f'{case["id"]}-flow.json').write_text(json.dumps(scenario,ensure_ascii=False,indent=2));csvout(ROOT/'examples'/f'{case["id"]}-events.csv',short);csvout(ROOT/'examples'/f'{case["id"]}-sponsors.csv',sponsor)
 desc=case['body']+'\n\nDirigido a: '+case['icp'].replace('Hipótesis: ','')+'.\n\nAgenda propuesta\n'+'\n'.join(t+' — '+v for t,v in case['agenda'])+'\n\nLa fecha, sede y facilitadores se anunciarán después de su confirmación. Las marcas citadas en el análisis no son sponsors confirmados de este encuentro. El seguimiento será opcional.'
 draft={'title':case['title'],'description':desc,'start_at':None,'end_at':None,'timezone':None,'location':None,'status':'local_editorial_draft_not_publishable_until_required_fields_confirmed','publication_target':'Luma','luma_event_id':None,'pending':pending}
 (ROOT/'examples'/f'{case["id"]}-luma-draft.json').write_text(json.dumps(draft,ensure_ascii=False,indent=2))
 (ROOT/'examples'/f'{case["id"]}-luma-draft.md').write_text('# '+case['title']+'\n\nBorrador editorial local. Fecha, sede y organizador pendientes de confirmar antes de publicar.\n\n'+desc+'\n')
 concept='concept_scale_'+case['id'];did='draft_scale_'+case['id']
 insert('event_concepts',{'id':concept,'title':case['title'],'objective':case['objective'],'audience':case['icp'],'format':'hands_on_workshop','proposed_location':'Berlin (scenario only)','rationale':'Derived from cited public profile and explicitly weighted shortlist; not measured demand','evidence_ids_json':js([profile['assertion_id']]),'estimated_budget':str(case['budget']),'currency':'EUR','pending_decisions_json':js(pending),'status':'hypothetical_local_proposal'})
 insert('luma_drafts',{'id':did,'concept_id':concept,'title':case['title'],'description':desc,'agenda_json':js(case['agenda']),'supported_fields_json':js({'public_profile_source':profile['source_url'],'draft_text':'authored proposal'}),'local_state':'requires_user_inputs_before_publish','version':'scale-v2.1','pending_decisions_json':js(pending),'luma_event_id':None})
 report+=['\n## '+case['company'],f'Empresa: [{case["url"]}]({case["url"]}). Perfil publicado: {profile["value"]}. [Fuente primaria]({profile["source_url"]}).',case['objective']+'. '+case['icp']+'. Presupuesto ilustrativo EUR '+str(case['budget'])+'; no es presupuesto disponible de la empresa.',f'Los archivos `{case["id"]}-flow.json`, `-events.csv`, `-sponsors.csv` y `-luma-draft.md/json` contienen el flujo íntegro, componentes del score, agenda, presupuesto y plan GTM. El borrador está listo para revisión/copia editorial, **no para publicación automática**: faltan fecha, sede e identidad de organizador confirmadas.']
report+=['\n## Evaluación','Los scores priorizan investigación dentro del corpus. No predicen compras, respuesta de sponsors, asistencia o ROI. Las listas de sponsors son hipótesis apoyadas en presencia histórica; un rival comercial puede resultar inadecuado. No se ha medido Precision@10 humana. La ventana de candidatos deja treinta días desde el corte para evitar recomendaciones ya pasadas o inmediatamente impracticables.']
(ROOT/'examples/README.md').write_text('\n\n'.join(report));csvout(ROOT/'maps/opportunities.csv',allrows)
(ROOT/'maps/opportunities.geojson').write_text(js({'type':'FeatureCollection','features':[{'type':'Feature','id':r['case']+':'+r['event_id'],'geometry':{'type':'Point','coordinates':[r['longitude'],r['latitude']]} if r['latitude'] is not None and r['longitude'] is not None else None,'properties':r} for r in allrows]}))
c.commit();print('2 flows,',len(allrows),'scored candidates, local drafts only')
