"""Logical delivery contract. Empty tables are schema-only, never fabricated facts."""
SCHEMA={
'sources':'id url canonical_url publisher title source_type language published_at observed_at access_method reuse_status extraction_status',
'assertions':'id entity_table entity_id field value_json source_id locator evidence_paraphrase valid_from valid_to observed_at evidence_class confidence_basis conflict_status',
'companies':'id name domain company_url aliases_json description industry products_json markets_json size_text missing_reasons_json source_id',
'event_series':'id name url identity_method periodicity source_id',
'event_editions':'id series_id title canonical_url start_date end_date start_at end_at timezone date_precision end_semantics status temporal_bucket location_raw country modality geo_precision venue_id format sector topics_json language registration_status last_verified source_id missing_reasons_json',
'event_company_roles':'id event_id company_id role level relationship_status valid_from valid_to source_id',
'sponsor_profiles':'id company_id objectives_json audiences_json categories_json geographies_json proposal_channel decision_process budget_amount currency missing_reasons_json source_id',
'sponsorship_packages':'id event_id name amount_min amount_max currency benefits_json exclusivity inventory availability valid_from valid_to deadline source_id',
'people':'id name professional_url missing_reasons_json source_id',
'participation':'id person_id event_id company_id role historical_job_title participation_status source_id',
'audience_metrics':'id event_id segment metric value unit denominator period method metric_status source_id',
'event_metrics':'id event_id company_id metric value unit denominator period attribution_method metric_status source_id',
'event_costs':'id event_id category amount_min amount_max currency unit taxes inclusions valid_from valid_to cost_status source_id',
'venues':'id name address city country latitude longitude geo_method geo_precision capacity capacity_format url business_channel source_id',
'distribution_channels':'id company_id name channel_type topic geography url access_terms declared_size size_observed_at source_id',
'competitors':'id name url category buyer capabilities_json availability data_coverage refresh integrations_json export_access public_price price_currency limitations source_id',
'extraction_queue':'id source_url family geography segment window_start window_end priority status last_processed cursor blocking_reason attempts next_action completion_condition',
'platform_listings':'id event_id platform native_id url first_observed last_observed listing_status evidence_method source_id',
'source_snapshots':'id source_id original_url archive_url capture_at observed_at content_type sha256 availability retained_material retention_basis',
'crawl_runs':'id method extractor_version scope started_at finished_at pages_attempted pages_completed pages_failed records_output measured_cost_usd billing_status closure_reason',
'fetch_attempts':'id run_id url observed_at result error_class duration_ms attempt_number next_step',
'search_queries':'id query service language filters_json geography window_start window_end observed_at new_sources_count batch_id',
'entity_aliases':'id entity_table entity_id alias external_system valid_from valid_to equivalence_reason review_status source_id',
'record_versions':'id entity_table entity_id version previous_value_json new_value_json valid_from valid_to observed_at source_id change_reason',
'data_conflicts':'id entity_table entity_id field assertion_ids_json resolution status reviewer source_id',
'taxonomy_terms':'id category term definition parent_id synonyms_json language version',
'entity_classifications':'id entity_table entity_id term_id origin method version reviewed_at source_id',
'sessions':'id event_id title description topic track format start_at end_at space_id agenda_version status source_id',
'session_participants':'id session_id person_id company_id role historical_affiliation status source_id',
'ticket_types':'id event_id name eligibility benefits_json payment_mode capacity currency source_id',
'ticket_price_history':'id ticket_id amount currency fees taxes sale_phase observed_at valid_from valid_to availability source_id',
'event_status_history':'id event_id previous_status new_status announced_at effective_at reason source_id',
'event_relations':'id from_event_id to_event_id relation_type origin source_id',
'venue_spaces':'id venue_id name configuration capacity services_json accessibility valid_from valid_to source_id',
'event_space_assignments':'id event_id session_id space_id start_at end_at status source_id',
'event_assets':'id event_id asset_type url author language published_at rights locator source_id',
'communities':'id name company_id topic geography url public_channels_json source_id',
'community_event_links':'id community_id event_id role valid_from valid_to source_id',
'company_profile_history':'id company_id version products_json value_proposition audiences_json markets_json size_text observed_at valid_from valid_to source_id',
'professional_affiliations':'id person_id company_id role valid_from valid_to event_id source_id',
'event_deadlines':'id event_id deadline_type date date_precision timezone status requirements source_id',
'distribution_metrics':'id channel_id metric value unit period scope method source_id',
'news_articles':'id source_id title publisher author url language published_at updated_at editorial_type summary event_date access_status',
'news_entity_links':'id article_id entity_table entity_id mention_type assertion_id valid_from valid_to source_id',
'news_dedup_clusters':'id article_id cluster_id original_article_id relationship independence_basis source_id',
'company_signals':'id company_id signal_type fact_date geography fact hypothesis source_id',
'market_context':'id region sector variable value unit period decision_link source_id',
'sponsorship_history':'id company_id event_id series_id package_id level period status modality amount currency source_id',
'sponsorship_deliverables':'id package_id agreement_id benefit_type description quantity unit promised_audience deadline compliance_criterion source_id',
'sponsorship_observations':'id agreement_id deliverable_id event_id observed_at observation status metrics_json source_id',
'partner_relationships':'id company_a_id company_b_id relationship_type stated_objective valid_from valid_to event_id source_id',
'sponsorship_renewals':'id company_id series_id previous_event_id next_event_id previous_level next_level classification coverage_basis method version input_ids_json cutoff',
'topic_trends':'id term_id geography sector period universe count normalized_value method version input_ids_json cutoff',
'audience_overlap':'id entity_a_id entity_b_id universe method denominator value unit period limitations version input_ids_json cutoff',
'opportunity_clusters':'id region audience topic format period observed_supply demand_evidence costs gaps method version input_ids_json cutoff',
'evaluation_cases':'id title case_type company_profile_json objective constraints_json cutoff candidate_universe label_origin split ground_truth_quality',
'recommendation_runs':'id case_id cutoff dataset_version method parameters_json model_version elapsed_ms measured_cost_usd billing_status',
'recommendation_candidates':'id run_id event_id eligibility score_components_json rank evidence_ids_json missing_fields_json explanation human_label',
'sponsor_match_scores':'id company_id event_id concept_id cutoff criteria_json constraints_json history score interest_status uncertainty method version input_ids_json',
'scoring_evaluations':'id evaluation_set method baseline metric sample_size value definition uncertainty limitations measurement_status',
'unit_economics_scenarios':'id volume frequency data_usd models_usd maps_usd storage_usd human_usd total_usd cost_per_useful_result assumptions_json estimate_or_measured',
'event_concepts':'id brief_id title objective audience format proposed_location proposed_date rationale evidence_ids_json estimated_budget currency pending_decisions_json status',
'luma_drafts':'id concept_id title description agenda_json supported_fields_json local_state version pending_decisions_json luma_event_id',
'draft_field_evidence':'id draft_id field value_json origin source_id approval_state',
'customer_briefs':'id customer_id website objective offer audience geography dates_json budget currency constraints_json priorities_json version',
'user_feedback':'id brief_id proposal_id feedback_type reason observed_at later_outcome_json'
}
DERIVED=set('sponsorship_renewals topic_trends audience_overlap opportunity_clusters evaluation_cases recommendation_runs recommendation_candidates sponsor_match_scores scoring_evaluations unit_economics_scenarios entity_classifications'.split())
PRIVATE=set('customer_briefs user_feedback'.split())
PROPOSED=set('event_concepts luma_drafts draft_field_evidence'.split())
def layer(table):
    return 'private-schemas' if table in PRIVATE else ('proposals' if table in PROPOSED else ('derived' if table in DERIVED else 'observed'))
def cols(table): return SCHEMA[table].split()
